language: node_js

sudo: false

env:
  - NODE_ENV=test

node_js:
  - 0.12
  - 0.10

before_script:
  - export PATH=$PATH:$PWD/node_modules/.bin

script:
  - npm run coverage

after_script:
  - cat coverage/lcov.info | coveralls

